# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3289c6d5ee944c9f6ede6e033f3ef818dffff26717b8bb27bcfd0bebffd8434ae1cd9512facefb4dfb1a4567a915370461574b3fd87c3bb0b2d7ae6dd972e907

test:
  secret_key_base: 4fcbf9486a27d586e8b4577709150c975ae0b2c13e67a1a1a87735ae00f2c0c41fd1763af9f2e2470887af26d35b8c232f4892f2060b13d95e044c9144cc8d20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
